import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/home/hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>KU3DS-Edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col">
          <Hero />
        </div>
      </Layout>
    </div>
  );
}
