import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import Hero from "../components/training/hero";
import Oculus from "../components/training/oculus";
import Caution from "../components/training/caution";
import Gugu from "../components/training/gugu";
import Confirm from "../components/training/confirm";

export default function Training() {
  return (
    <div>
      <Head>
        <title>KU3DS-Edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col">
          <Hero />
          <Oculus></Oculus>
          <Caution></Caution>
          <Confirm></Confirm>
        </div>
      </Layout>
    </div>
  );
}
