import Head from "next/head";
import Gugu from "../components/education/gugu";
import Hero from "../components/education/hero";
import Layout from "../components/layout";

export default function Main() {
  return (
    <div>
      <Head>
        <title>KU-3DS</title>
        <meta name="KU-3DS" content="Generated by KU-3DS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gugu />
      <div className="min-h-screen bg-white"></div>
    </div>
  );
}
