import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/home/hero";
import ContentLaunch from "../components/home/content-launch";
import LaunchButton from "../components/home/button";
import Earth from "../components/home/earth";
import Intro from "../components/home/intro";

export default function Main() {
  return (
    <div>
      <Head>
        <title>KU-3DS</title>
        <meta name="KU-3DS" content="Generated by KU-3DS" />
        <link rel="icon" href="/favicon.ico" />ㅈ
      </Head>

      <Layout>
        <div className="bg-black">
          <Intro />
          <Earth />
          <Hero />
          <ContentLaunch />
          <LaunchButton />
        </div>
      </Layout>
    </div>
  );
}
