import Head from "next/head";
import Image from "next/image";
import AnimationMoon from "../components/animation/animation-moon";
import Layout from "../components/layout";

export default function Invitaion() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="KU-3DS" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="object-cover">
          <AnimationMoon />
        </div>
      </Layout>
    </div>
  );
}
