import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import ContentPlanet from "../components/planet/content-planet";
import Hero from "../components/planet/hero";
import Vr from "../components/planet/vr";

export default function Main() {
  return (
    <div>
      <Head>
        <title>KU-3DS</title>
        <meta name="KU-3DS" content="Generated by KU-3DS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="bg-black">
          <Hero />
          <Vr />
          <ContentPlanet />
        </div>
      </Layout>
    </div>
  );
}
